version: "3.4"
services:

  db:
    image: postgres:12-alpine
    restart: always
    expose:
      - 5432
    environment:
      - "POSTGRES_PASSWORD=clojure"
      - "POSTGRES_USER=clojure"
      - "POSTGRES_DB=clojure"

  ui:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "always"
    ports:
      - "3449:3449"
      - "7888:7888"
    environment:
      - "DB_HOST=db"
      - "WEB_HOST=0.0.0.0"
    depends_on:
      - db